// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKFhcF4D9WIayceKkmfU1sHc7hIS0f3zQ',
    appId: '1:171982874288:web:54e892a8722ee708c8fd75',
    messagingSenderId: '171982874288',
    projectId: 'skyways-defb3',
    authDomain: 'skyways-defb3.firebaseapp.com',
    storageBucket: 'skyways-defb3.firebasestorage.app',
    measurementId: 'G-7K5DG3XNY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGChrEMLpM5luDfverNh5BRhUOwfQAB3g',
    appId: '1:171982874288:android:b63e2ac61db2661bc8fd75',
    messagingSenderId: '171982874288',
    projectId: 'skyways-defb3',
    storageBucket: 'skyways-defb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_6Nybb2_AP0WqOh7GKJfhoL9nC3zjw7w',
    appId: '1:171982874288:ios:385579ac6b94bd67c8fd75',
    messagingSenderId: '171982874288',
    projectId: 'skyways-defb3',
    storageBucket: 'skyways-defb3.firebasestorage.app',
    iosBundleId: 'com.skyways.skyways',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKFhcF4D9WIayceKkmfU1sHc7hIS0f3zQ',
    appId: '1:171982874288:web:453fe634fcbe2edfc8fd75',
    messagingSenderId: '171982874288',
    projectId: 'skyways-defb3',
    authDomain: 'skyways-defb3.firebaseapp.com',
    storageBucket: 'skyways-defb3.firebasestorage.app',
    measurementId: 'G-FCCSH2175V',
  );
}
